### ISSUE TITLE
arch_list[-1] += '+PTX' IndexError: list index out of range

### ISSUE THREAD

**Issue by derrick-xwp** [sunset1995/DirectVoxGO#55]
export CUDA_VISIBLE_DEVICES=0 && python run.py --config configs/nerf/materials_dense_200.py --render_test

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.4'
/home/comp/enter/envs/dvg/lib/python3.7/site-packages/mmcv/__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
Using /home/comp.cache/torch_extensions/py37_cpu as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/comp/.cache/torch_extensions/py37_cpu/adam_upd_cuda/build.ninja...
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    from lib import utils, dvgo, dcvgo, dmpigo
  File "/home/comp/DirectVoxGO/lib/utils.py", line 11, in <module>
    from .masked_adam import MaskedAdam
  File "/home/comp/DirectVoxGO/lib/masked_adam.py", line 10, in <module>
    verbose=True)
  File "/home/comp/enter/envs/dvg/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1219, in load
    keep_intermediates=keep_intermediates)
  File "/home/comp/enter/envs/dvg/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1440, in _jit_compile
    is_standalone=is_standalone)
  File "/home/comp/enter/envs/dvg/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1538, in _write_ninja_file_and_build_library
    is_standalone=is_standalone)
  File "/home/comp/enter/envs/dvg/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1927, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "/home/comp/enter/envs/dvg/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1699, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

**Comment by cmy76** [comment]
I encoutered the same problem, and I found out that my torch is CPU version😂

**Comment by gkouros** [comment]
It's either what @cmy76 suggested or you have to the env variable CUDA_VISIBLE_DEVICES is empty (=-1), in which case you can just do the following if you have only one GPU:
```shell
export CUDA_VISIBLE_DEVICES=0
```

**Comment by zhouilu** [comment]
try like
export TORCH_CUDA_ARCH_LIST="8.6"
