### ISSUE TITLE
The custom CUDA extensions may be uncompatible with PyTorch 1.10.0, possible missing dependency `ninja`

### ISSUE THREAD

**Issue by fxmarty** [sunset1995/DirectVoxGO#9]
Hello,

I run the training in a google colab instance.

My code is roughly the following:

```
from google.colab import drive
drive.mount('/content/drive')

%cd "drive/My Drive/"

pip install -r requirements.txt

import torch
assert(torch.__version__ == '1.10.0+cu111')

pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu111.html

!python run.py --config configs/blendedmvs/Jade.py --render_test  # train
```

First error coming out (in the last line of the above), I need `ninja`:

```
Using /root/.cache/torch_extensions/py37_cu111 as PyTorch extensions root...
Creating extension directory /root/.cache/torch_extensions/py37_cu111/adam_upd_cuda...
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    from lib import utils, dvgo
  File "/content/drive/MyDrive/MAREVA_project/DirectVoxGO/lib/utils.py", line 11, in <module>
    from .masked_adam import MaskedAdam
  File "/content/drive/MyDrive/MAREVA_project/DirectVoxGO/lib/masked_adam.py", line 10, in <module>
    verbose=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 1136, in load
    keep_intermediates=keep_intermediates)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 1347, in _jit_compile
    is_standalone=is_standalone)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 1418, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 1474, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions
```

Then, I do

```
pip install ninja
```

Rerunning the line `!python run.py --config configs/blendedmvs/Jade.py --render_test  # train`, I now get a very ugly output, that I put on pastebin because it is too long: https://pastebin.com/Lc8a8ngj . Notice that despite the warnings, the training starts at the end.

Is this output expected?

Thanks a lot!

**Comment by sunset1995** [comment]
Thanks for reminding me the dependency :)

Yes, this is expected when the first time you run the code where I turn on the verbose mode of Pytorch jit compilation module for debugging purpose.

**Comment by fxmarty** [comment]
Great to know - I'll use the version with the custom kernels then. Thanks!

**Comment by aarrushi** [comment]
Hi,
I tried "pip install ninja" but still getting the issue "raise RuntimeError("Ninja is required to load C++ extensions")".

**Comment by sunset1995** [comment]
It seems that window OS have some issues with this.
Maybe can try this [https://github.com/zhanghang1989/PyTorch-Encoding/issues/167](https://github.com/zhanghang1989/PyTorch-Encoding/issues/167).

**Comment by Learningm** [comment]
I solved this problem "RuntimeError("Ninja is required to load C++ extensions")" by installing
1. torch 1.8.1, cuda 11.1
2. pip install ninja
3. sudo apt-get install ninja-build

**Comment by aarrushi** [comment]
@Learningm did you resolve it on windows as well?

**Comment by Learningm** [comment]
@aarrushi I resolved it on Linux.
